---

- name: peer prob from one node
  shell: |
    "gluster peer probe {{ slave_node1 }}"
    "gluster peer probe {{ slave_node1 }}"

- name: get the full path of the volume
  set_fact:
    s_path: "{{ export_dir }}/{{ volume_name }}"

- name: "create gluster volume {{ volume_name }}"
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ volume_name }}"
    bricks: "{{ export_dir }}"
    rebalance: yes
    cluster:
      - "{{ master_node }}"
      - "{{ slave_node1 }}"
      - "{{ slave_node2 }}"
  run_once: true

- name: "start gluster volume {{ volume_name }}"
  gluster.gluster.gluster_volume:
    state: started
    name: "{{ volume_name }}"

- debug: msg="Mount by the following command = mount -t glusterfs {{ ansible_default_ipv4.address }}:{{ volume_name }} /mnt"
