---


- name: install the system packages
  package:
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: "create a ext2 filesystem on {{ export_device }}"
  community.general.filesystem:
    fstype: xfs
    dev: "{{ export_device }}"

- name: "create export directory {{ export_dir }}"
  file: 
    name: "{{ export_dir }}"
    state: directory
    recurse: yes

- name: "create volume directory {{ volume_name }}"
  file: 
    name: "{{ volume_name }}"
    state: directory
    recurse: yes

- name: mount the device to the directory
  mount:
    path: "{{ export_dir }}"
    src: "{{ export_device }}"
    fstype: xfs
    dump: 1
    passno: 2
    state: present

- name: enable and start the gluster service
  service:
    name: glusterd
    state: restarted
    enabled: yes

- name: entry on fs table on admin node to accept the request
  shell: |
    "iptables -I INPUT -p all -s {{ master_node }} -j ACCEPT"
    "iptables -I INPUT -p all -s {{ slave_node1 }} -j ACCEPT"
    "iptables -I INPUT -p all -s {{ slave_node2 }} -j ACCEPT"
